mysite/mysite/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import password_reset
from django.conf.urls import url

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    url(r'password_reset/$', password_reset, {'template_name': 'registration/password_reset.html'}, name="password_reset"),
]

mysite/mysite/mysite/urls.py
from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin
from accounts.views import home

urlpatterns = [
    path('', home),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

mysite/mysite/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

mysite/mysite/accounts/models.py
from django.db import models

# Create your models here.

mysite/mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/mysite/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

mysite/mysite/accounts/views.py
from django.shortcuts import render
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect

from . forms import SignUpForm

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('login')
    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form': form})

def home(request):
    return render(request, 'accounts/home.html')

mysite/mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(
        	 pub_date__lte=timezone.now()
       	).order_by('-pub_date')


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/index.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

    def get_context_data(self, **kwargs):
        context = super(ResultsView, self).get_context_data(**kwargs)
        votes = 0
        choices = Choice.objects.filter(question__id=self.kwargs['pk'])
        for choice in choices:
        	votes = votes + choice.votes
        context['totalvotes'] = votes
        
        return context

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		pass  #alert is handled in javascript
	else:
		selected_choice.votes += 1;
		selected_choice.save()
		return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

mysite/mysite/accounts/templates/accounts/home.html
{% extends 'polls/base.html' %}

{% block title %}Home{% endblock %}
{% block content %}
	{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/home.css' %}">
    <h1 id="big-text" class="animated tada">clash.</h1>
    <h2>"Let the ideas clash but not the hearts."</h2>
    <div id="home-links">
    	<a href="/accounts/login">Login</a> <i class="fa fa-bolt" aria-hidden="true"></i>
    	<a href="{% url 'accounts:signup'%}">Sign up</a>
    </div>
    <script type="text/javascript" >
	    $(document).ready(function(){
			$("#big-text").hover(function(){
		       	$(this).addClass('animated tada');
		        }, function(){
		        $(this).removeClass('animated tada');
		    });
	    });
	</script>
{% endblock %}

mysite/mysite/accounts/templates/accounts/signup.html
{% extends 'polls/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'polls/css/login-signup.css' %}">

	<div class="login-page">
		<div class="form">
			{% for field in form.visible_fields %}
			    {% for err in field.errors %}
			    	<span class="error-message">{{ err }}</span>
			    {% endfor %}
			{% endfor %}
			
			<form method="post">
				{% csrf_token %}
				{% for field in form %}
				    <div class="register-form">
				        {{ field }}
				    </div>
				{% endfor %}
				<button type="submit">Sign up</button>
				<p class="message">Already registered? <a href="{% url 'login'%}">Sign In</a></p>
			</form>
		</div>
	</div>

	<script type="text/javascript" >
	    $(document).ready(function(){
	        $("#id_username").attr('placeholder', '{{form.username.label}}');
	        $("#id_email").attr('placeholder', '{{form.email.label}}');
	        $("#id_password1").attr('placeholder', '{{form.password1.label}}');
	        $("#id_password2").attr('placeholder', 'Confirm password');
	    });
	</script>
{% endblock %}

mysite/mysite/polls/templates/polls/base.html
<html>
<head>
	{% load static %}
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<!-- Google fonts -->
	<link href="https://fonts.googleapis.com/css?family=Londrina+Solid" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">

    <!-- JQuery -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<!-- Bootstrap core CSS -->
	<link href="{% static 'polls/css/bootstrap.min.css' %}" rel="stylesheet">
	<!-- Material Design Bootstrap -->
	<link href="{% static 'polls/css/mdb.min.css' %}" rel="stylesheet">
    <!-- Sweetalert -->
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
	<!-- Your custom styles (optional) -->
	<link href="{%static 'polls/css/style.css' %}" rel="stylesheet">
	<title>{% block title %}Django Tutorials{% endblock %}</title>
</head>
<body>
	<!--Main Navigation-->
	<header>
	    <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark default-color scrolling-navbar">
        	{% if user.is_authenticated %}
            	<a class="navbar-brand" href="{% url 'polls:index' %}" title="Polls"><strong class="logo">clash.</strong></a>
            {% else %}
            	<a class="navbar-brand" href="/"><strong class="logo" title="Home Page">clash.</strong></a>
            {% endif %}
            <!-- Dropdown menu -->
            
            <ul class="nav navbar-nav nav-flex-icons ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-user"></i> <span class="clearfix d-none d-sm-inline-block">Account</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                    	<a class="dropdown-item" href="{% url 'accounts:password_reset' %}">Reset Password</a>
                    	{% if user.is_authenticated %}
                            <a class="dropdown-item" href="{% url 'polls:index' %}">Polls Home</a>
                    		<a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                        {% else %}
                        	<a class="dropdown-item" href="{% url 'accounts:signup' %}">Sign Up</a>
                            <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                        {% endif %}
                    </div>
                </li>
            </ul>
            <!-- Dropdown menu -->

        </nav>
        <!-- Navbar -->

	</header>
	<!--Main Navigation-->

	<main>
	{% block content %}
	{% endblock %}
	</main>
	<!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'polls/js/jquery-3.3.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'polls/js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'polls/js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'polls/js/mdb.min.js' %}"></script>
</body>
</html>

mysite/mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block title %}Polls App{% endblock %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

    {% if user.is_authenticated %}
        {% if latest_question_list %}
        	<!-- <ul>
        		{% for question in latest_question_list %}
        			<li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
        		{% endfor %}
        	</ul> -->

            <!-- Container wrapper -->
            <div class="container-wrapper">
                <!-- Card deck -->
                <div class="card-columns">
                    <!-- Card -->
                    {% for question in latest_question_list %}
                        <div class="card mb-4">
                        <!--Card content-->
                        <div class="card-body">
                            <!--Title-->
                            <h4 class="card-title font-weight-bold"><a href="{% url 'polls:results' question.id %}" class="teal-text" title="View Results">{{question.question_text}}</h4>
                            <hr class="hr-dark">
                            <!--Text-->
                            <p class="card-text">{{question.pub_date}}</p>

                            <!-- Choices -->
                            <!-- <div class="funkyradio">
                                <div class="funkyradio-primary">
                                    <input type="radio" name="radio" id="radio1" checked/>
                                    <label for="radio1">Do</label>
                                </div>
                                <div class="funkyradio-primary">
                                    <input type="radio" name="radio" id="radio2" checked/>
                                    <label for="radio2">Die</label>
                                </div>
                            </div> -->
                            <!-- Choices -->
                            <form action="{% url 'polls:vote' question.id %}" method="post">
                                {% csrf_token %}
                                <div class="funkyradio">
                                    {% for choice in question.choice_set.all %}
                                        <div class="funkyradio-primary">
                                            <input type="radio" name="choice" id="choice{{question.id}}{{ forloop.counter }}" value="{{ choice.id }}"/>
                                            <label for="choice{{question.id}}{{ forloop.counter }}" title="{{ choice.choice_text }}">{{ choice.choice_text }}</label>
                                        </div>
                                    {% endfor %}
                                </div>
                                <button type="button submit" class="btn btn-default btn-lg btn-block" id="submitButton">VOTE</button>
                            </form>
                        </div>
                        </div>
                    {% endfor %}
                    <!-- Card -->
                </div>
                <!-- Card deck -->
            </div>
            <!-- Container wrapper -->

            <script type="text/javascript">
                // When your page is ready, wire up these events
                $(function () {
                    // When your submit button is clicked
                    $("form").submit(function (e) {
                        // If it is not checked, prevent the default behavior (your submit)
                        if (!$('input[name="choice"]').is(':checked')) {
                            swal({text: "Please ensure a choice is selected!", icon:"error"});
                            e.preventDefault();
                        }
                    });
                });
            </script>
        {% else %}
        	<p>No polls are available.</p>
            <style>
                body {
                    background: #E0E0E0;
                }
                p {
                    text-align: center;
                    font-family: 'Open Sans', sans-serif;
                    color: #A0A0A0;
                }
            </style>
        {% endif %}
        <!-- <p><a href="{% url 'logout' %}">logout</a></p> -->
    {% else %}
        <p>You are not logged in.</p>
        <div id="home-links">
            <a href="/accounts/login">Login</a> <i class="fa fa-bolt" aria-hidden="true"></i>
            <a href="{% url 'accounts:signup'%}">Sign up</a>
        </div>
        <style>
            body {
                background: #E0E0E0;
            }
            p {
                text-align: center;
                font-family: 'Open Sans', sans-serif;
                color: #A0A0A0;
            }
            #home-links {
                width: 250px;
                margin: auto;
                border-top: 1px dotted;
                padding-top: 8px;
            }

            #home-links a {
                margin: 0px 25px;
                font-family: 'Pacifico', cursive;
                font-size: 20px;
            }
        </style>
    {% endif %}
{% endblock %}

mysite/mysite/polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block title %}{{question.question_text}}{% endblock %}

{% block content %}
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'polls/css/results.css' %}">

	{% load polls_extras %}
	<div class="container-results z-depth-4">
		<h1>{{question.question_text}}</h1>
		<hr class="hr-dark">
		<!-- <ul>
			{% for choice in question.choice_set.all %}
				<li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
			{% endfor %}
		</ul> -->
		<div class="span4">
			{% for choice in question.choice_set.all %}
				<div class="one_result">
					<strong class="choice_text" style="color: #2E8B57;">{{choice.choice_text}}</strong><strong class="votes">({{choice.votes}} vote{{choice.votes|pluralize}})</strong>
					<div class="progress-bar" role="progressbar" aria-valuenow="{{choice.votes}}"
					aria-valuemin="0" aria-valuemax="{{totalvotes}}" style="width:{{ totalvotes|computePercent:choice.votes}}%; background: #006D5B;">
						{{ totalvotes|computePercent:choice.votes}}%
					</div>
				</div>
			{% endfor %}
			<p id="total_votes">= {{totalvotes}}</p>
		</div>
		<!-- <a href="{% url 'polls:index' %}">Vote again?</a> -->
		<button onclick="location.href = '{% url 'polls:index' %}';" type="submit" class="btn-outline-primary waves-effect" title="Polls Home">Vote Again</button>

	</div>
{% endblock %}